name: "🍎 Nova Oferta de Excedente"
description: Use este formulário para registrar alimento excedente.
title: "[Oferta] {{ item }} – {{ escola }}"
labels: [oferta-disponivel]
body:
  - type: input
    id: escola_codinep
    attributes:
      label: Código INEP da escola
      placeholder: "e.g. 11000001"
    validations: { required: true }
  - type: input
    id: item
    attributes: { label: Produto, placeholder: "Arroz tipo 1 – 5 kg" }
    validations: { required: true }
  - type: input
    id: quantidade
    attributes: { label: Quantidade, placeholder: "12 kg" }
    validations: { required: true }
  - type: input
    id: validade
    attributes: { label: Data de validade (DD/MM/AAAA) }
    validations: { required: true }
  - type: textarea
    id: observacoes
    attributes: { label: Observações adicionais, placeholder: "Lote lacrado, armazenado em local seco." }
